name: BungeeSignsPremium
version: 2.1
main: me.Bentipa.BungeeSigns.BSignsMain
author: Bentipa
commands:


   bsinfo:
      description: Informations.
      usage: /<command>
      permission: BungeeSigns.info
      
   bsupdate:
      description: Update the Plugin.
      usage: /<command>
      permission: BungeeSigns.update
      
   createBSSign:
     description: Create a FreeFight-Connection-Sign.
     usage: /<command>
     permission: BungeeSigns.create
     
   removeBSSign:
     description: Remove a FreeFight-Connection-Sign.
     usage: /<command>
     permission: BungeeSigns.remove
      
   bsreload:
     description: Reloads the config.
     usage: /<command>
     permission: BungeeSigns.reload    